JOIN_EVENT = "JOIN"
LEAVE_EVENT = "LEAVE"
MSG_EVENT = "MSG"
CONNECT_EVENT = 'CONNECTION ESTABLISHED'
DISCONNECT_EVENT = 'CONNECTION LOST'
IGNORE_EVENT = 'IGNORE'
UNIGNORE_EVENT = "UNIGNORE"
NICK_EVENT = "NICK"
CTCPQUERY_EVENT = "CTCP"

EVENTS = (JOIN_EVENT, LEAVE_EVENT, MSG_EVENT, CONNECT_EVENT,
 DISCONNECT_EVENT, IGNORE_EVENT, UNIGNORE_EVENT, NICK_EVENT)
